### ISSUE TITLE
[Suggestion] Arrangement should be sorted by date 

### ISSUE THREAD

**Issue by UbadahJ** [SalmanFarooqShiekh/ArrangementsFinder#2]
The assignments should be sorted by their dates so that it is easier to read. Currently, the arrangements appear to be randomly displayed for the end-users

**Comment by salman-farooq-sh** [comment]
Thank you for your feedback. 

I have sorted them by date now. Sorting by time is still not done.

**Comment by salman-farooq-sh** [comment]
Sorting by time done.

**Comment by UbadahJ** [comment]
That's good! Maybe the next step should be an overall better UI or even better a mobile application that can set alarms and notifications for you and syncs the arrangements from a specific online site. I can help you with wireframes and Android application if you are interested

**Comment by salman-farooq-sh** [comment]
Ah, I intend to not spend more time on this thing. 

But, you are always welcome to fork out something new or make something from the group up.
